name: App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_script:
    name: Build script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: shopify/shopify-cli-action
        with:
          command: 'version'
  build_extension:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: shopify/shopify-cli-action@0.1.0
        with:
          command: 'version'