name: App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_script:
    name: Build script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Replace with https://github.com/shopify/shopify-cli-action once it's public
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
      - name: Install Shopify CLI
        run: gem install shopify-cli
  build_extension:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Replace with https://github.com/shopify/shopify-cli-action once it's public
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
      - name: Install Shopify CLI
        run: gem install shopify-cli