name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_script:
    name: Build script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Replace with https://github.com/shopify/shopify-cli-action once it's public
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Shopify CLI
        run: gem install shopify-cli
      - name: Install dependencies
        run: |
          yarn install --cwd scripts/payment_method
      - name: Deploy
        working-directory: scripts/payment_method
        run: echo "Not implemented yet"
  deploy_extension:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Replace with https://github.com/shopify/shopify-cli-action once it's public
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Shopify CLI
        run: gem install shopify-cli
      - name: Install dependencies
        run: |
          yarn install --cwd ui-extensions/checkout_post_purchase
      - name: Deploy
        uses: shopify/shopify-cli-action@v1
        with:
          command: 'extension push --api-key=$API_KEY --api-secret=$API_SECRET --registration-id=$EXTENSION_ID'
